/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krismorte.escala2.view;

import com.krismorte.escala2.model.Analista;
import com.krismorte.escala2.model.Equipe;
import com.krismorte.escala2.model.Nivel;
import com.krismorte.escala2.service.CrudService;
import com.krismorte.escala2.util.BeanTableModel;
import com.krismorte.escala2.util.MyJTable;
import com.krismorte.escala2.util.ScreenUtil;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author c007329
 */
public class TelaAnalista extends javax.swing.JDialog {

    private CrudService crudService = new CrudService();
    private List<Equipe> equipes = new ArrayList<>();
    private List<Analista> analistas = new ArrayList<>();
    private MyJTable tabelaAnalistas;

    /**
     * Creates new form TelaAnalista
     */
    public TelaAnalista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        iniciaRadio();
        equipes = crudService.listarEquipes();
        analistas = crudService.listarAnalistas();
        iniciaBox();
        exibeTabela();
    }

    private void iniciaBox() {
        equipes.forEach(equipe -> boxEquipe.addItem(equipe.getNome()));
    }

    private void iniciaRadio() {
        ButtonGroup grp = new ButtonGroup();
        grp.add(radPleno);
        grp.add(radSenior);
        radPleno.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxEquipe = new javax.swing.JComboBox<>();
        radSenior = new javax.swing.JRadioButton();
        radPleno = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        panelAnalistas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Analista");

        jLabel1.setText("Nome:");

        jLabel2.setText("Equipe:");

        radSenior.setText("Senior");

        radPleno.setText("Pleno");

        btnSalvar.setText("salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        panelAnalistas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelAnalistasLayout = new javax.swing.GroupLayout(panelAnalistas);
        panelAnalistas.setLayout(panelAnalistasLayout);
        panelAnalistasLayout.setHorizontalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAnalistasLayout.setVerticalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAnalistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(boxEquipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radSenior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radPleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radSenior)
                        .addComponent(radPleno))
                    .addComponent(btnSalvar))
                .addGap(18, 18, 18)
                .addComponent(panelAnalistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome e esolha os horários");
        } else {
            try {
                Analista analista = new Analista();
                analista.setNome(txtNome.getText());
                Equipe eqp = null;
                for (Equipe equipe : equipes) {
                    if (equipe.getNome().equals(boxEquipe.getSelectedItem().toString())) {
                        eqp = equipe;
                        break;
                    }
                }
                analista.setEquipe(eqp);
                if (radSenior.isSelected()) {
                    analista.setNivel(Nivel.Senior);
                } else {
                    analista.setNivel(Nivel.Pleno);
                }
                crudService.salvarAnalista(analista);
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                txtNome.setText("");
                analistas = crudService.listarAnalistas();
                exibeTabela();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void exibeTabela() {
        BeanTableModel<Analista> modelo = new BeanTableModel<>(Analista.class);
        modelo.addColumn("nome", "nome", BeanTableModel.EditMode.EDITABLE);
        modelo.addColumn("equipe", "equipe");
        modelo.addColumn("Active", "active");

        for (Analista m : analistas) {
            modelo.addRow(m);
        }

        tabelaAnalistas = new MyJTable(modelo);
        //tabelaHorarios.addMouseListener(new MouseEventMenu(menuDirect));
        panelAnalistas.removeAll();
        panelAnalistas.setLayout(new GridLayout(1, 1));

        //tabela = reTweetService.getJTable(listaTweets);
        panelAnalistas.add(ScreenUtil.getJScroll(tabelaAnalistas), BorderLayout.CENTER);
        panelAnalistas.validate();
        //txtTotal.setText("" + horarios.size());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAnalista dialog = new TelaAnalista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEquipe;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelAnalistas;
    private javax.swing.JRadioButton radPleno;
    private javax.swing.JRadioButton radSenior;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
