package com.krismorte.escala2.view;

import com.krismorte.escala2.model.Equipe;
import com.krismorte.escala2.service.CrudService;
import com.krismorte.escala2.util.Tradutor;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.TransferHandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author c007329
 */
public class Tela extends javax.swing.JFrame {

    private LocalDate mesAtual;
    private List<DNDLabelPanel> panels = new ArrayList<>();
    private List<Equipe> equipes = new ArrayList<>();
    private CrudService crudService = new CrudService();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        init();
    }

    private void init() {
        splitPanel.setDividerLocation(200);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        mesAtual = LocalDate.of(LocalDateTime.now().getYear(), LocalDateTime.now().getMonthValue(), 1);
        panelAnalistas.setLayout(new GridLayout(20, 1));
        panelAnalistas.setOpaque(false);
        panelAnalistas.add(getLabel("Krisnamourt da silva C filho - C007329"));
        panelAnalistas.add(getLabel("Chico Renan"));

        loadBox();
        updateMoth(mesAtual);
    }

    private void loadBox() {
        equipes = crudService.listarEquipes();
        equipes.forEach(equipe -> boxEquipe.addItem(equipe.getNome()));
    }

    private void updateMoth(LocalDate data) {
        labelMes.setText(mesAtual.format(Tradutor.getMothFormater()) + "/" + mesAtual.getYear());
        panelCalendario.removeAll();
        panelCalendario.setLayout(new GridLayout(1, 1));
        panelCalendario.add(new JPanelMes(data));
    }

    /*private void updateMoth(LocalDate data) {
        panelCalendario.removeAll();
        int ultimoDiaDoMes = LocalDate.now().with(TemporalAdjusters.lastDayOfMonth()).getDayOfMonth();
        
        labelMes.setText(data.getMonth().toString()+"/"+data.getYear());
        
        panelCalendario.setLayout(new GridLayout(2, 7));
        panelCalendario.setOpaque(false);        
        for (int i = 1; i <= ultimoDiaDoMes; i++) {
            if (data.getDayOfWeek().toString().equals("SATURDAY") || data.getDayOfWeek().toString().equals("SUNDAY")) {
                //panelCalendario.add(getPanel(data.getDayOfMonth() + " " + data.getDayOfWeek()));
                panelCalendario.add(new JPanelDia(data.getDayOfMonth() + " " + data.getDayOfWeek(), horarios));
            }

            data = data.plusDays(1);
        }
    }*/

 /*private DNDImagePanel getDNDImagePane(String title) {
        DNDImagePanel pane1 = new DNDImagePanel(title);
        panels.add(pane1);
        return pane1;
    }*/
 /*private DNDLabelPanel getPanel(String title) {
        if (title.contains("SATURDAY")) {
            title = title.replace("SATURDAY", "SAB");
        } else if (title.contains("SUNDAY")) {
            title = title.replace("SUNDAY", "DOM");
        }
        DNDLabelPanel pane1 = new DNDLabelPanel(new AcaoJPanel(), title);
        panels.add(pane1);
        return pane1;
    }*/
    private JLabel getLabel(String text) {
        JLabel label = new JLabel(text);
        final String propertyName = "text";
        label.setTransferHandler(new TransferHandler(propertyName));

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                JComponent comp = (JComponent) evt.getSource();
                TransferHandler th = comp.getTransferHandler();

                th.exportAsDrag(comp, evt, TransferHandler.COPY);
            }
        });

        return label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        panelCalendario = new javax.swing.JPanel();
        panelAnalistas = new javax.swing.JPanel();
        btnAfter = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        labelMes = new javax.swing.JLabel();
        btnHorario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        boxEquipe = new javax.swing.JComboBox<>();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCalendarioLayout = new javax.swing.GroupLayout(panelCalendario);
        panelCalendario.setLayout(panelCalendarioLayout);
        panelCalendarioLayout.setHorizontalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        panelCalendarioLayout.setVerticalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(panelCalendario);

        javax.swing.GroupLayout panelAnalistasLayout = new javax.swing.GroupLayout(panelAnalistas);
        panelAnalistas.setLayout(panelAnalistasLayout);
        panelAnalistasLayout.setHorizontalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAnalistasLayout.setVerticalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        splitPanel.setLeftComponent(panelAnalistas);

        btnAfter.setText("<");
        btnAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfterActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        labelMes.setBackground(new java.awt.Color(255, 255, 255));
        labelMes.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        labelMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMes.setText("jLabel1");
        labelMes.setOpaque(true);

        btnHorario.setText("horario");
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });

        jButton2.setText("equipe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("analista");

        btnGerar.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHorario)
                        .addContainerGap())
                    .addComponent(splitPanel, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfter)
                    .addComponent(btnNext)
                    .addComponent(labelMes)
                    .addComponent(btnHorario)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(boxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        mesAtual = mesAtual.plusMonths(1);
        updateMoth(mesAtual);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfterActionPerformed
        mesAtual = mesAtual.minusMonths(1);
        updateMoth(mesAtual);
    }//GEN-LAST:event_btnAfterActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        TelaHorario horario = new TelaHorario(this, true);
        horario.setLocationRelativeTo(null);
        horario.setVisible(true);
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaEquipe equipe = new TelaEquipe(this, true);
        equipe.setLocationRelativeTo(null);
        equipe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEquipe;
    private javax.swing.JButton btnAfter;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel labelMes;
    private javax.swing.JPanel panelAnalistas;
    private javax.swing.JPanel panelCalendario;
    private javax.swing.JSplitPane splitPanel;
    // End of variables declaration//GEN-END:variables
}
