package com.krismorte.escala2.view;

import com.krismorte.escala2.model.Analista;
import com.krismorte.escala2.model.Equipe;
import com.krismorte.escala2.model.Horario;
import com.krismorte.escala2.service.CrudService;
import com.krismorte.escala2.util.Tradutor;
import com.towel.combo.swing.ObjectComboBoxModel;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author c007329
 */
public class Tela extends javax.swing.JFrame {
    
    private ObjectComboBoxModel<Equipe> boxModel;
    private List<DNDLabelPanel> panels = new ArrayList<>();
    
    private LocalDate mesAtual;
    private List<Analista> analistas;
    private List<Equipe> equipes = new ArrayList<>();
    private List<Horario> horarios = new ArrayList<>();
    private CrudService crudService = new CrudService();

    /**
     * Creates new form Tela
     */
    public Tela(boolean ConexaoOk) {
        initComponents();
        init();
        if (!ConexaoOk) {
            JOptionPane.showMessageDialog(null, "Falha na conexão com banco de dados");
            btnEquipe.setEnabled(false);
            btnHorario.setEnabled(false);
            btnAnalista.setEnabled(false);
            boxEquipe.setEnabled(false);
        }
    }
    
    private void init() {
        setLogo();
        loadBox();
        splitPanel.setDividerLocation(200);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        panelAnalistas.setLayout(new GridLayout(20, 1));
        panelAnalistas.setOpaque(false);
        mesAtual = LocalDate.of(LocalDateTime.now().getYear(), LocalDateTime.now().getMonthValue(), 1);
    }
    
    private void setLogo() {
        try {
            setIconImage(ImageIO.read(ClassLoader.getSystemResource("img/calendar-20-20.png")));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadBox() {
        equipes = crudService.listarEquipes();
        boxModel = new ObjectComboBoxModel<Equipe>();
        boxModel.setData(equipes);
        boxEquipe.setModel(boxModel);
        boxEquipe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (boxModel.getSelectedObject() != null) {
                    loadJLabel();
                    atualizaCalendario(mesAtual);
                }
            }
        });
    }
    
    private void loadJLabel() {
        analistas = crudService.listarAnalistasPorEquipe(boxModel.getSelectedObject());
        panelAnalistas.removeAll();
        panelAnalistas.revalidate();
        panelAnalistas.repaint(); // sometimes needed, this appears to be one of them
        //analistas.forEach(analista -> panelAnalistas.add(getLabel(analista.getNome())));
        //analistas.forEach(analista -> panelAnalistas.add(new JLabelAnalista(analista)));
        analistas.forEach(analista -> panelAnalistas.add(JLabelAnalista.transferable(analista)));
    }
    
    private void atualizaCalendario(LocalDate data) {
        if (boxModel.getSelectedObject() != null) {
            horarios = crudService.listarHorariosPorEquipe(boxModel.getSelectedObject());
        }
        labelMes.setText(mesAtual.format(Tradutor.getMothFormater()) + "/" + mesAtual.getYear());
        panelCalendario.removeAll();
        panelCalendario.setLayout(new GridLayout(1, 1));
        panelCalendario.add(new JPanelMes(data, boxModel.getSelectedObject(), analistas, horarios));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        panelCalendario = new javax.swing.JPanel();
        panelAnalistas = new javax.swing.JPanel();
        btnAfter = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        labelMes = new javax.swing.JLabel();
        btnHorario = new javax.swing.JButton();
        btnEquipe = new javax.swing.JButton();
        btnAnalista = new javax.swing.JButton();
        boxEquipe = new javax.swing.JComboBox<>();
        btnService = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Escalas");

        javax.swing.GroupLayout panelCalendarioLayout = new javax.swing.GroupLayout(panelCalendario);
        panelCalendario.setLayout(panelCalendarioLayout);
        panelCalendarioLayout.setHorizontalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        panelCalendarioLayout.setVerticalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(panelCalendario);

        javax.swing.GroupLayout panelAnalistasLayout = new javax.swing.GroupLayout(panelAnalistas);
        panelAnalistas.setLayout(panelAnalistasLayout);
        panelAnalistasLayout.setHorizontalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAnalistasLayout.setVerticalGroup(
            panelAnalistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        splitPanel.setLeftComponent(panelAnalistas);

        btnAfter.setText("<");
        btnAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfterActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        labelMes.setBackground(new java.awt.Color(255, 255, 255));
        labelMes.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        labelMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMes.setText("jLabel1");
        labelMes.setOpaque(true);

        btnHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHorario.setText("horario");
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });

        btnEquipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEquipe.setText("equipe");
        btnEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipeActionPerformed(evt);
            }
        });

        btnAnalista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnalista.setText("analista");
        btnAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalistaActionPerformed(evt);
            }
        });

        btnService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/service-20-20.png"))); // NOI18N
        btnService.setToolTipText("sistema");
        btnService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnService)
                        .addContainerGap())
                    .addComponent(splitPanel, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHorario)
                    .addComponent(btnEquipe)
                    .addComponent(btnAnalista)
                    .addComponent(btnService))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPanel))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(boxEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelMes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAfter)))
                .addGap(564, 564, 564))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnalista, btnEquipe, btnHorario, btnService});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        mesAtual = mesAtual.plusMonths(1);
        atualizaCalendario(mesAtual);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfterActionPerformed
        mesAtual = mesAtual.minusMonths(1);
        atualizaCalendario(mesAtual);
    }//GEN-LAST:event_btnAfterActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        TelaHorario horario = new TelaHorario(this, true);
        horario.setLocationRelativeTo(null);
        horario.setVisible(true);
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipeActionPerformed
        TelaEquipe equipe = new TelaEquipe(this, true);
        equipe.setLocationRelativeTo(null);
        equipe.setVisible(true);
        loadBox();
    }//GEN-LAST:event_btnEquipeActionPerformed

    private void btnAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalistaActionPerformed
        TelaAnalista equipe = new TelaAnalista(this, true);
        equipe.setLocationRelativeTo(null);
        equipe.setVisible(true);
    }//GEN-LAST:event_btnAnalistaActionPerformed

    private void btnServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceActionPerformed
        TelaSistema sis = new TelaSistema(this, true);
        sis.setLocationRelativeTo(null);
        sis.setVisible(true);
    }//GEN-LAST:event_btnServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEquipe;
    private javax.swing.JButton btnAfter;
    private javax.swing.JButton btnAnalista;
    private javax.swing.JButton btnEquipe;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnService;
    private javax.swing.JLabel labelMes;
    private javax.swing.JPanel panelAnalistas;
    private javax.swing.JPanel panelCalendario;
    private javax.swing.JSplitPane splitPanel;
    // End of variables declaration//GEN-END:variables
}
